jobs:
  build:
    name: Run build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Use cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: '${{ runner.os }}-maven3-

          '
    - continue-on-error: true
      name: Configure Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Run Maven
      run: mvn clean install --batch-mode -PintegrationTests
      shell: bash
    - continue-on-error: true
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
        OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
      if: github.repository_owner == 'eirslett' && github.ref == 'refs/heads/master'
        && matrix.os == 'ubuntu-latest'
      name: Deploy
      run: 'export GPG_TTY=$(tty)

        echo -e "$GPG_KEY" | gpg --import --passphrase $GPG_PASSPHRASE --batch --yes

        mvn --settings settings-github.xml -B deploy -Prelease -DskipTests

        '
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
name: Build
on:
  repository_dispatch:
    types: trigger-ga___main.yml
